// @flow

export const ADD_TRACK_TO_QUEUE = 'ADD_TRACK_TO_QUEUE';
export const DELETE_TRACK_FROM_QUEUE = 'DELETE_TRACK_FROM_QUEUE';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const INCREMENT_REPEAT_TIMES = 'INCREMENT_REPEAT_TIMES';
export const DECREMENT_REPEAT_TIMES = 'DECREMENT_REPEAT_TIMES';
